(function (global) {
   'use strict';

   var DS = global.DeckSuggest;
   var deriveSwapQueue = global.SwapQueue.deriveSwapQueue;

   function buildExport(state) {
      var run = state.generationRun;
      if (!run || !run.deckResults || !run.deckResults.length) {
         throw new Error('No generation results to export.');
      }
      var setScope = state.setScope;
      var today = new Date().toISOString().slice(0, 10);
      var decks = run.deckResults.map(function (result) {
         var deck = result.deck;
         var queue = deriveSwapQueue(deck);
         return {
            deck_id: deck.deck_id,
            deck_name: deck.deck_name,
            archidekt_url: deck.archidekt_url || '',
            format: deck.format || 'commander',
            analysis: {
               swap_queue: result.analysis && result.analysis.swap_queue
                  ? result.analysis.swap_queue
                  : DS.buildSwapQueueAnalysis(deck),
               inferred_themes: (deck.profile && deck.profile.tags) || []
            },
            suggestions: DS.sortSuggestions(result.suggestions || []),
            deck_snapshot: deck.deck_snapshot || null,
            profile_preferences: deck.profile_preferences || {
               protected_cards: (deck.profile && deck.profile.protected_cards) || [],
               blocked_cards: (deck.profile && deck.profile.blocked_cards) || []
            },
            skipped: result.skipped || false,
            skip_reason: result.skip_reason || null
         };
      });

      return {
         meta: {
            schema_version: '1.1',
            set_code: setScope.primaryCode,
            set_name: setScope.setName,
            set_codes: setScope.codes,
            sets: setScope.codes.map(function (code) {
               return { code: code, name: code, set_type: 'expansion', card_count: setScope.cards.length };
            }),
            generated_at: today,
            card_count: setScope.cards.length,
            notes: 'Generated by Deck Suggest (rule-based); no LLM.'
         },
         decks: decks
      };
   }

   function downloadJson(state) {
      var payload = buildExport(state);
      return HubUtils.downloadSuggestionsJson(payload);
   }

   function buildSummary(st) {
      var run = st.generationRun;
      if (!run || !run.deckResults) {
         return null;
      }
      var totalSwap = 0;
      var totalNormal = 0;
      var skippedQueue = 0;
      var deckRows = [];
      (run.deckResults || []).forEach(function (result) {
         var list = result.suggestions || [];
         var swap = 0;
         var normal = 0;
         list.forEach(function (s) {
            if (s.priority_tier === 'swap') {
               swap += 1;
            } else {
               normal += 1;
            }
         });
         totalSwap += swap;
         totalNormal += normal;
         deckRows.push({
            deck_id: result.deck.deck_id,
            deck_name: result.deck.deck_name,
            swap: swap,
            normal: normal,
            total: list.length,
            skipped: !!result.skipped,
            error: result.error || null,
            message: result.message || null
         });
      });
      (run.rulesExecuted || []).forEach(function (a) {
         if (a.skippedReason && String(a.skippedReason).indexOf('not_in_set_scope') >= 0) {
            skippedQueue += 1;
         }
      });
      var setScope = st.setScope || {};
      return {
         totalSuggestions: totalSwap + totalNormal,
         totalSwap: totalSwap,
         totalNormal: totalNormal,
         deckRows: deckRows,
         skippedQueueSlots: skippedQueue,
         setCodes: setScope.codes || [],
         poolSize: (setScope.cards || []).length
      };
   }

   function hasReviewableSuggestions(st) {
      if (!st.generationRun) {
         return false;
      }
      try {
         var payload = buildExport(st);
         return (payload.decks || []).some(function (d) {
            return (d.suggestions || []).length > 0;
         });
      } catch (e) {
         return false;
      }
   }

   DS.Export = {
      buildExport: buildExport,
      buildSummary: buildSummary,
      hasReviewableSuggestions: hasReviewableSuggestions,
      downloadJson: downloadJson
   };
})(window);
