(function (global) {
   'use strict';

   var DS = global.DeckSuggest;
   var deriveSwapQueue = global.SwapQueue.deriveSwapQueue;

   function buildExport(state) {
      var run = state.generationRun;
      if (!run || !run.deckResults || !run.deckResults.length) {
         throw new Error('No generation results to export.');
      }
      var setScope = state.setScope;
      var today = new Date().toISOString().slice(0, 10);
      var decks = run.deckResults.map(function (result) {
         var deck = result.deck;
         var queue = deriveSwapQueue(deck);
         return {
            deck_id: deck.deck_id,
            deck_name: deck.deck_name,
            archidekt_url: deck.archidekt_url || '',
            format: deck.format || 'commander',
            analysis: {
               swap_queue: result.analysis && result.analysis.swap_queue
                  ? result.analysis.swap_queue
                  : DS.buildSwapQueueAnalysis(deck),
               inferred_themes: (deck.profile && deck.profile.tags) || []
            },
            suggestions: DS.sortSuggestions(result.suggestions || []),
            deck_snapshot: deck.deck_snapshot || null,
            profile_preferences: deck.profile_preferences || {
               protected_cards: (deck.profile && deck.profile.protected_cards) || [],
               blocked_cards: (deck.profile && deck.profile.blocked_cards) || []
            },
            skipped: result.skipped || false,
            skip_reason: result.skip_reason || null
         };
      });

      return {
         meta: {
            schema_version: '1.1',
            set_code: setScope.primaryCode,
            set_name: setScope.setName,
            set_codes: setScope.codes,
            sets: setScope.codes.map(function (code) {
               return { code: code, name: code, set_type: 'expansion', card_count: setScope.cards.length };
            }),
            generated_at: today,
            card_count: setScope.cards.length,
            notes: 'Generated by Deck Suggest (rule-based); no LLM.'
         },
         decks: decks
      };
   }

   function downloadJson(state) {
      var payload = buildExport(state);
      var date = payload.meta.generated_at;
      var filename = payload.meta.set_code + '-' + date + '-rules.json';
      var blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
      var url = URL.createObjectURL(blob);
      var a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);
      return filename;
   }

   DS.Export = {
      buildExport: buildExport,
      downloadJson: downloadJson
   };
})(window);
